baseURL = "https://saul-larios.github.io/my_launchx_blog/"
languageCode = "en-us"
title = "Bitácora de Viaje"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = "G-MB8KJ1DHDH"
  # Hey Explorer aquí pon tu twitter 👇
  twitter_handle = "@KingdomHam"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
